# Generated by Django 4.2.2 on 2024-12-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
